postsubmits:
  khulnasoft/fanal/test-infra:
  - name: update-jobs-pr
    decorate: true
    path_alias: github.com/khulnasoft/fanal/test-infra
    agent: kubernetes
    branches:
      - ^master$
    spec:
      serviceAccountName: update-jobs
      containers:
      - image: docker.io/khulnasoft/test-infra/update-jobs:latest
        imagePullPolicy: Always
        command:
        - /go/bin/update-jobs
        - --jobs-config-path
        - /home/prow/go/src/github.com/khulnasoft/fanal/test-infra/config/jobs
      nodeSelector:
        Archtype: "x86"
