name: push-ci-images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'ui/**'

jobs:
  build-push-image:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v3.5.3

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.20'
          check-latest: true
          cache: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2.9.1

      - uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1

      - uses: anchore/sbom-action/download-syft@f325610c9f50a54015d37c8d16cb3b0e2c8f4de0 # v0.18.0

      - uses: goreleaser/goreleaser-action@336e29918d653399e599bfca99fadc1d7ffbc9f7 # v4.3.0
        with:
          install-only: true

      - name: run goreleaser-snapshot
        run: |
          make goreleaser-snapshot
          docker images
          docker run khulnasoft/fanal/ui:latest-amd64 -v
          docker run docker.io/khulnasoft/fanal/ui:latest-amd64 -v
        env:
          GOPATH: /home/runner/go

      # Push images to DockerHUB
      - name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push images to Dockerhub
        run: |
          docker push khulnasoft/fanal/ui:latest-amd64
          docker push khulnasoft/fanal/ui:latest-arm64
          docker push khulnasoft/fanal/ui:latest-armv7
          docker manifest create --amend khulnasoft/fanal/ui:latest khulnasoft/fanal/ui:latest-amd64 \
            khulnasoft/fanal/ui:latest-arm64 khulnasoft/fanal/ui:latest-armv7
          docker manifest push --purge khulnasoft/fanal/ui:latest

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@fc3959cb4cf5a821ab7a5a636ea4f1e855b05180 # v1.6.2
        with:
          registry-type: public

      - run: |
          docker push docker.io/khulnasoft/fanal/ui:latest-amd64
          docker push docker.io/khulnasoft/fanal/ui:latest-arm64
          docker push docker.io/khulnasoft/fanal/ui:latest-armv7
          docker manifest create --amend docker.io/khulnasoft/fanal/ui:latest docker.io/khulnasoft/fanal/ui:latest-amd64 \
            docker.io/khulnasoft/fanal/ui:latest-arm64 docker.io/khulnasoft/fanal/ui:latest-armv7
          docker manifest push --purge docker.io/khulnasoft/fanal/ui:latest
