name: push-ci-images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'ui/**'

jobs:
  build-push-image:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: '1.22'
          check-latest: true
          cache: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0

      - uses: anchore/sbom-action/download-syft@df80a981bc6edbc4e220a492d3cbe9f5547a6e75 # v0.17.9

      - uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          install-only: true

      - name: run goreleaser-snapshot
        run: |
          make goreleaser-snapshot
          docker images
          docker run khulnasoft/fanal:latest-amd64 --version
          docker run docker.io/khulnasoft/fanal:latest-amd64 --version
        env:
          GOPATH: /home/runner/go

      # Push images to DockerHUB
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push images to Dockerhub
        run: |
          docker push khulnasoft/fanal:latest-amd64
          docker push khulnasoft/fanal:latest-arm64
          docker push khulnasoft/fanal:latest-armv7
          docker manifest create --amend khulnasoft/fanal:latest khulnasoft/fanal:latest-amd64 \
            khulnasoft/fanal:latest-arm64 khulnasoft/fanal:latest-armv7
          docker manifest push --purge khulnasoft/fanal:latest

      # Push images to AWS Public ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::292999226676:role/github_actions-fanal-ecr
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: public

      - run: |
          docker push docker.io/khulnasoft/fanal:latest-amd64
          docker push docker.io/khulnasoft/fanal:latest-arm64
          docker push docker.io/khulnasoft/fanal:latest-armv7
          docker manifest create --amend docker.io/khulnasoft/fanal:latest docker.io/khulnasoft/fanal:latest-amd64 \
            docker.io/khulnasoft/fanal:latest-arm64 docker.io/khulnasoft/fanal:latest-armv7
          docker manifest push --purge docker.io/khulnasoft/fanal:latest
