name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    name: Run unit tests
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.22'
          check-latest: true
          cache: true
      - name: Run Go tests
        run: make test
